# Generated by Django 6.1.1 on 2026-10-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_academicsession_course_result_accesscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
